### ISSUE TITLE
Ubuntu Wily Werewolf [server-state]

### ISSUE THREAD

**Issue by elcore** [scaleway/initrd#100]
While booting the Server the following Problems occur:

```
>>> ´scw-update-server-state kernel-started´ failed
>>> ´scw-update-server-state booted´ failed
```
Ubuntu Wily Werewolf
Linux Kernel 4.2.5-std

**Comment by moul** [comment]
@QuentinPerez found the issue, I will fix this today

**Comment by moul** [comment]
A new initrd was just released, can you try again ?

**Comment by elcore** [comment]
The Problem is sloved

**Comment by moul** [comment]
Cool, we should improve the current hack during next week
