### ISSUE TITLE
Please bump version

### ISSUE THREAD

**Issue by albertdb** [scaleway/initrd#164]
Hi,

I'm eager to try the new kexec features. Could you please release a new version including those features that are already in master?

Thank you very much,

Albert

**Comment by moul** [comment]
Hi @albertdb, yep, I need to check if the new support is actually usable without having a custom bootscript, and add some documentation, certainly tomorrow

**Comment by moul** [comment]
v3.11 is released: https://github.com/scaleway/initrd/releases/tag/v3.11
Build PR: https://github.com/scaleway/qa/pull/636

We will update the existing bootscripts to use the new initrd soon

**Comment by QuentinPerez** [comment]
Hi @albertdb 

v3.12.1 is released and available ☺️
I close this issue
