### ISSUE TITLE
KEXEC: append parameters to cmdline

### ISSUE THREAD

**Issue by albertdb** [scaleway/initrd#168]
Hi,

There's only one thing missing in kexec support that would enable autosufficient installation and bootup of custom OS: appending custom parameters to cmdline used in kexec.

So, it would be awesome if you could add a tag to specify extra cmdline parameters.

Thank you very much,

Albert

**Comment by albertdb** [comment]
@moul Any chance of implemementing this on short-term please? Having a quick look at the sources, seems quite simple to add the functionality. Thanks!

**Comment by moul** [comment]
Hi @albertdb, #170 should make you happy :)

**Comment by albertdb** [comment]
Thank you very much!!!

**Comment by moul** [comment]
@QuentinPerez is releasing a new version

**Comment by QuentinPerez** [comment]
It will be available soon https://travis-ci.org/scaleway/qa/builds/170155970
