### ISSUE TITLE
Run systemd from initrd and handle shutdown

### ISSUE THREAD

**Issue by moul** [scaleway/initrd#31]
Dummy todo (extracted from http://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/)

- [x] mount /run as a tmpfs and pass it pre-mounted when jumping into the main system when executing systemd. The mount options should be mode=755,nodev
- [ ] it's highly recommended that the initrd also mounts /usr (if split off) as appropriate and passes it pre-mounted to the main system, to avoid the problems described in Booting without /usr is Broken.
- [x] If the executable /run/initramfs/shutdown exists systemd will use it to jump back into the initrd on shutdown.
- [x] /run/initramfs should be a usable initrd environment to which systemd will pivot back and the "shutdown" executable in it should be able to detach all complex storage that for example was needed to mount the root file system. It's the job of the initrd to set up this directory and executable in the right way so that this works correctly. The shutdown binary is invoked with the shutdown verb as argv[1], optionally followed (in argv[2], argv[3], ...) by systemd's original command line options, for example --log-level= and similar.
- [ ] Storage daemons run from the initrd should follow the the guide on systemd and Storage Daemons for the Root File System to survive properly from the boot initrd all the way to the point where systemd jumps back into the initrd for shutdown.
- [x] One last clarification: we use the term initrd very generically here describing any kind of early boot file system, regardless whether that might be implemented as an actual ramdisk, ramfs or tmpfs. We recommend using initrd in this sense as a term that is unrelated to the actual backing technologies used.
- [ ] It is also possible and recommended to implement the initrd itself based on systemd. Here are a few terse notes:
  - [ ] Provide /etc/initrd-release in the initrd image. The idea is that it follows the same format as the usual /etc/os-release but describes the initial RAM disk implementation rather than the OS. systemd uses the existence of this file as a flag whether to run in initial RAM disk mode, or not.
  - [ ] When run in initrd mode, systemd and its components will read a couple of additional command line arguments, which are generally prefixed with rd.
  - [ ] To transition into the main system image invoke "systemctl switch-root".
  - [ ] The switch-root operation will result in a killing spree of all running processes. Some processes might need to be excluded from that, see the guide on systemd and Storage Daemons for the Root File System.

---

Related to:
- online-labs/image-fedora#15
- online-labs/image-fedora#17

**Comment by moul** [comment]
Also related to http://www.freedesktop.org/wiki/Software/systemd/RootStorageDaemons/

**Comment by esmil** [comment]
You don't necessarily have to run systemd in the initrd. I guess the easiest way to do a clean shutdown is to have a staticly linked shell, xnbd-client and umount.
Then your boot-nbd script can just copy the shell, xnbd-client, and umount to /run/initramfs/ along with a /run/initramfs/shutdown script to run
`
#!sh
umount /dev/nbd0
xnbd-client --disconnect /dev/nbd0
`

**Comment by moul** [comment]
Very interesting thanks, we will try this soon !

**Comment by esmil** [comment]
Ok, I played around with this a little. It turns out you don't have to put stuff in /run/initramfs from the initrd. As long as it is there when systemd shuts down it will exec /run/initramfs/shutdown.

I've played around with this a bit. Try spinning up the image 121970ab-f7bf-44e6-abc0-c14727a8b974 and notice that it boots properly :)

**Comment by esmil** [comment]
Ugh. I meant notice that it _reboots_ properly.

**Comment by moul** [comment]
Fixed
