### ISSUE TITLE
Populate a /etc/hosts in the initrd, in the same fashion as /etc/hostname

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/initrd#52]
Why we need this:

- some applications do a gethostbyname() on the hostname to retrieve the external IP of the machine (hadoop)
- unfortunately, it is currently bound to 127.0.0.1, it fails,
- we have different behaviors between our distributions, we should probably have a unique behavior on all distros here

What docker does:

    root@30cc5c8df063:/code# cat /etc/hosts
    172.17.0.164	30cc5c8df063
    127.0.0.1	localhost

The proposal is to do the same: populate /etc/hosts with the private IP address of the server.

ping @edouardb

**Comment by moul** [comment]
see discussion here: https://github.com/scaleway/initrd/issues/33

**Comment by moul** [comment]
Closing it, for now, if your image need it, put it in a script in the image

**Comment by moul** [comment]
Fixed by #156
