### ISSUE TITLE
Autoconnect volumes in rescue mode

### ISSUE THREAD

**Issue by brmzkw** [scaleway/initrd#94]
The rescue image doesn't connect extra volumes automatically and you have to run `/run/initramfs/usr/sbin/xnbd-client -C /dev/nbdXX IP PORT`.

It would be nice to:
- have xnbd-client in $PATH
- have volumes automatically connected (but not mounted)

**Comment by moul** [comment]
* `xnbd-client` won't be in `$PATH`
* volumes will be automatically attached but not mounted
