### ISSUE TITLE
api-metadata: `request error [429] too many requests` when editing `userdata`

### ISSUE THREAD

**Issue by QuentinPerez** [scaleway/initrd#96]
When I try to boot a pimouss with the newest initrd
I can't set any data to ```169.254.42.42``` because the API returns an error **429**

**Comment by moul** [comment]
The error is "too many request"

Can be tested using:

```console
$ scw run --rm --bootscript=rescue alpine
root@dreamy-cray:~# /run/initramfs/usr/bin/scw-update-server-state -u root_password=test
REQUEST ERROR [403]
root@dreamy-cray:~# /run/initramfs/usr/bin/scw-update-server-state -u root_password=test
REQUEST ERROR [403]
root@dreamy-cray:~# /run/initramfs/usr/bin/scw-update-server-state -u root_password=test
REQUEST ERROR [429]
```

**Comment by moul** [comment]
This issue is now closed, but the solution is ugly, and the boot time is now 10 seconds longer

**Comment by brmzkw** [comment]
Even though you will always need to handle the HTTP/429 response, our rate limiting should be less aggressive.

**Comment by moul** [comment]
Checkout our jabber, I just asked you this :)
